### ISSUE TITLE
Feature request: Add worked example that enables ssh connectivity into the VM

### ISSUE THREAD

**Issue by petemounce** [veertuinc/packer-builder-veertu-anka#11]
We use packer in combination with the `ansible` packer provisioner to provision the VMs before capturing them as images.

It would be really handy to see a worked example of how to achieve this. I _imagine_ the options we have look like
* find a way for the existing packer `ansible` provisioner's temporary keys to be used (this would be our preference)
* find a way to poke a public key into the authorized_keys file of the `anka` user

**Comment by asafg6** [comment]
added with this commit: https://github.com/veertuinc/packer-builder-veertu-anka/commit/3681983d5a9eb8e74c53cda4b9205d4d6921b23a

**Comment by petemounce** [comment]
@asafg6 that isn't really what I was asking for.

I would like to be able to use a template like

```json
{
  "builders": [
    {
      "type": "veertu-anka",
      "disk_size": "{{user `disk_size`}}",
      "ram_size": "{{user `ram_size`}}",
      "cpu_count": "{{user `cpu_count`}}",
      "vm_name": "{{user `vm_name`}}",
      "installer_app": "/Applications/Install macOS {{ user `installer_app` }}.app/"
    }
  ],
  "provisioners": [
    {
      "type": "ansible",
      "user": "anka",
      "playbook_file": "playbook.yml"
    }
  ]
}
```

and have that run to completion successfully.

Note that I am starting from an `installer_app` base-OS start; that's the crucial aspect for me.

I would _ideally_ want the plugin to generate a temporary private key locally, then add that private key's public key into `/Users/anka/.ssh/authorized_keys` so that ssh pubkey auth is used throughout.
