### ISSUE TITLE
Bug: packer 1.5.1 fails to run plugin 1.0.2 and 1.1.0

### ISSUE THREAD

**Issue by petemounce** [veertuinc/packer-builder-veertu-anka#16]
I have the plugin inside ~/.packer.d/plugins, it's +x, and when I try a packer build I get a permission-denied error.

If I revert from packer 1.5.1 to packer 1.4.5 my builds work as before.

```
+ packer build -color=false -var ansible_debug_output=true -var ansible_diff_mode=always -var ansible_verbosity=-v -var cpu_count=2 -var disk_size=256G -var image_platform=macos -var imp_private_key_path=/var/folders/w2/jd7cgbj92n9b3xbzkp5rft740000gn/T/tmp.z4afaiDk/private_key -var installer_app=/Users/petermounce/.cache/bakery/mojave/10.14.06/install-macos-mojave-10.14.06.app -var ram_size=8G -var ssh_config_path=/var/folders/w2/jd7cgbj92n9b3xbzkp5rft740000gn/T/tmp.hapl2FYG -var version=14.6.06 -var vm_name=macos_14.6.06ssh9 ./macos_bare.packer.json
Failed to initialize build 'veertu-anka': error initializing builder 'veertu-anka': fork/exec /usr/local/bin: permission denied
```

**Comment by asafg6** [comment]
@petemounce, can you share a bit more details about your environment?

**Comment by asafg6** [comment]
also, I see that 1.5.1 is a pre-release. have you tried 1.5.0?

**Comment by petemounce** [comment]
> can you share a bit more details about your environment?

Sure - what would you like to know?

* macOS Mojave 10.14.6
* veertu plugins 1.0.2 and 1.1.0

I haven't tried packer 1.5.0; it doesn't seem to be available inside homebrew.

```
$ git -C $(brew --repo homebrew/core) log -10 -- Formula/packer.rb
Sun Dec 22 09:01:00 2019 +0000 44f21fa03 packer: update 1.5.1 bottle.  [BrewTestBot]
Sat Dec 21 19:16:36 2019 -0500 c1b237241 packer 1.5.1  [Caleb Xu]
Tue Nov 5 00:03:07 2019 +0000 afdf78612 packer: update 1.4.5 bottle.  [BrewTestBot]
Mon Nov 4 18:00:02 2019 -0500 c2abcff53 packer 1.4.5  [Rui Chen]
Wed Oct 2 17:09:50 2019 +0000 68d11f707 packer: update 1.4.4 bottle.  [BrewTestBot]
Wed Oct 2 09:15:20 2019 +1000 481d797a9 packer 1.4.4  [Igor Kapkov]
Sat Aug 17 23:02:44 2019 +0000 af31e5e3a packer: update 1.4.3 bottle.  [BrewTestBot]
Sat Aug 17 12:32:53 2019 -0700 844d6b2db packer 1.4.3  [Christian Barcenas]
Sun Aug 4 14:50:25 2019 +0000 53c2222a1 packer: update 1.4.2 bottle.  [BrewTestBot]
Fri Aug 2 17:04:23 2019 +0200 d7caec0d6 packer 1.4.2  [Ahmed Hazem]
```

It sounds like (from a different error), the plugin API version has changed

```
Failed to initialize build 'googlecompute': error initializing provisioner 'goss': Incompatible API version with plugin. Plugin version: 4, Ours: 5
```

That's a provisioner plugin, not a builder plugin. I had a quick look inside the packer docs but am unfamiliar with writing plugins; is that something you can check out?

I downgraded to packer 1.4.5 via `cd "$(brew --repo homebrew/core)" && git checkout afdf78612 && HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall packer`

**Comment by asafg6** [comment]
@petemounce 
Apparently there was some breaking changes in 1.5.
there's a discussion about it [here]( https://github.com/hashicorp/packer/issues/8527#issuecomment-568000559 )
We will add this to our dev pipeline, in the meantime you will have to use 1.4.5 .
sorry for the inconvenience

**Comment by petemounce** [comment]
Ah, no worries. I see there is a fix inside the pending 1.5.2 already.
Thanks for investigating.

**Comment by kuhnroyal** [comment]
Using the current packer nightly with the permission fix there still an API level error.

```
Failed to initialize build 'veertu-anka': error initializing builder 'veertu-anka': Incompatible API version with plugin. Plugin version: 4, Ours: 5
```

**Comment by asafg6** [comment]
hi @kuhnroyal 
updating the plugin to the new object interface is in our dev pipeline.
will update here when it's out.

**Comment by NivKeidan** [comment]
Version 1.2.0 is now compatible with packer 1.5.X
