### ISSUE TITLE
Make anka user that VM has match `anka config default_user` setting

### ISSUE THREAD

**Issue by petemounce** [veertuinc/packer-builder-veertu-anka#19]
With plugin 1.2.0, I see that the anka user is created `Anka`. My anka flow is configured to suggest that it will be `anka`, note lowercase.

This means that if I try to use `anka` (via looking it up via `anka config default_user`), ssh fails against `anka@127.0.0.1` compared to succeeding against `Anka@127.0.0.1`.

Can the plugin use the `anka config default_user` value, matching case, by default when creating the user inside the VM, when `installer_app` is specified? For both the user's human readable name and system-identifier name?

Alternatively, is there something else I could look into to figure out why this isn't working as I expected?

Upper-case:

![Screen Shot 2020-04-08 at 14 26 09](https://user-images.githubusercontent.com/69720/78789338-eb72fb00-79a4-11ea-90d4-040b3026e099.png)

vs lower-case:

```
$ anka run macos_10.15.4 dscl . list /Users | grep -v "^_"
anka
daemon
nobody
root
```

and 

```
$ anka run macos_10.15.4 ls -al /Users/
total 0
drwxr-xr-x   5 root  admin  160 Apr  7 03:37 .
drwxr-xr-x  22 root  admin  704 Apr  7 03:34 ..
-rw-r--r--   1 root  wheel    0 Feb 28 22:21 .localized
drwxrwxrwt   4 root  wheel  128 Apr  7 03:39 Shared
drwxr-xr-x  10 anka  staff  320 Apr  8 06:29 anka
```

**Comment by NorseGaud** [comment]
Hey @petemounce, just wanted to confirm a few things:
1. You're using Anka Flow instead of Build?
2. What versions are you using of the above Anka CLI version?

**Comment by petemounce** [comment]
I'm using

```
$ anka version
Anka Flow version 2.2.2 (build 116)

$ packer version
Packer v1.5.4

$ ~/.packer.d/plugins/packer-builder-veertu-anka
panic: Please do not execute plugins directly. Packer will execute these for you.

goroutine 1 [running]:
main.main()
	/Users/anka/workspace/build-packer_release_v1.2.0/src/github.com/veertuinc/packer-builder-veertu-anka/main.go:11 +0xa1
```

on macOS Catalina 10.15.4, and using a 10.15.4 installer.

**Comment by NorseGaud** [comment]
Solved by using `anka run -n -N`
