### ISSUE TITLE
Cannot install Big Sur from .app

### ISSUE THREAD

**Issue by tduffield** [veertuinc/packer-builder-veertu-anka#23]
I get the following when I try to use the packer builder to build a Big Sur VM: 

```
Build 'veertu-anka' errored: Bad or unsupported macOS installer
```

Is this expected, given the relative "newness" of Big Sur? I'm running packer 1.6.0 and plugin v1.3.0

**Comment by medicis123** [comment]
Hi - Currently you can't use anka create to create VM from the Big Sur app installer. You can only take an existing Anka VM and do the upgrade to Big Sur from inside the VM manually.

**Comment by tduffield** [comment]
Awesome, thank you for the follow up. I'd like to keep this issue open until that is resolved if possible.

**Comment by danielbayley** [comment]
> Currently you can't use anka create to create VM from the Big Sur app installer. You can only take an existing Anka VM and do the upgrade to Big Sur from inside the VM manually.

@medicis123 Is this likely to be resolved any time soon?

**Comment by NorseGaud** [comment]
@danielbayley , this is now possible using our 2.3.0-beta release: https://veertu.com/anka-develop-with-big-sur-support/

Though this release is still in beta and there are still a few items to resolve in the code. See "Known Issues" under the release notes: https://ankadocs.veertu.com/docs/release-notes/#anka-virtualization-cli-230-beta-118166----03-2020

**Comment by NorseGaud** [comment]
We're out of beta now so this should be working just fine.
