### ISSUE TITLE
Feature request: re-use a base VM if installer_app is specified.

### ISSUE THREAD

**Issue by petemounce** [veertuinc/packer-builder-veertu-anka#31]
At present, creating a VM by starting with from a macOS installer has a long iteration time because of the time it takes to create the base VM from the installer.

Since the installer should create mostly-the-same base VM each time it's run (modulo software updates of the moment at the time of run), cache it.

There should be a simple way to clear this cache to force a from-scratch VM.

(PR incoming)

**Comment by NorseGaud** [comment]
Will be included in 1.6.0
