### ISSUE TITLE
[security integrity] SHASUM for v1.5.0 is wrong

### ISSUE THREAD

**Issue by marco-m-pix4d** [veertuinc/packer-builder-veertu-anka#34]
hello,
according to https://github.com/veertuinc/packer-builder-veertu-anka/releases/download/v1.5.0/packer-builder-veertu-anka_1.5.0_checksums.txt:

```
476ee2873e6274ed6610f405eef247d99079f7257331514d8972c5109e955096  packer-builder-veertu-anka_v1.5.0_darwin_amd64.zip
```

But it is actually:

```
shasum -a 256 packer-builder-veertu-anka_v1.5.0_darwin_amd64.zip
e899a04c6977ba693305b8062bdda31674e6079459854fa9590dbbd0127fdd5b  packer-builder-veertu-anka_v1.5.0_darwin_amd64.zip
```

**Comment by NorseGaud** [comment]
It's possible our goreleaser is not doing what it's supposed to in our CI/CD. I will check and follow up.

**Comment by marco-m-pix4d** [comment]
Thanks @NorseGaud, appreciated.

**Comment by NorseGaud** [comment]
Ok, I found the issue. The checksum happens pre-signing, so it will never match. We'll just remove it since goreleaser doesn't seem to have an alternative/order we can use.

**Comment by marco-m-pix4d** [comment]
Hello, did you consider https://goreleaser.com/customization/sign/#archives ? Its _seems_ there is a way, but I didn't check in details.

**Comment by NorseGaud** [comment]
> Hello, did you consider https://goreleaser.com/customization/sign/#archives ? Its _seems_ there is a way, but I didn't check in details.

Correct -- we tried all of the available options and they didn't work. We're working with the goreleaser team to figure this out.
