### ISSUE TITLE
Feature Request: Add verbose output during provisioning of base vm

### ISSUE THREAD

**Issue by joshenders** [veertuinc/packer-builder-veertu-anka#8]
I'm not sure if this is possible with the method packer-builder-veertu-anka is using to install macOS but it would be helpful if a user were able to monitor the progress during macOS installation. As designed currently, the time elapsed between line 2 and line 3 is about 45 minutes.

```
01| ==> veertu-anka: Creating a temporary directory for sharing data...
02| ==> veertu-anka: Creating a new vm from installer, this will take a while
03| ==> veertu-anka: VM anka-base-KoueizFgPi was created (12f760f5-68ad-11e8-98dd-f200014b19c5)
04| ==> veertu-anka: Cloning source VM anka-base-KoueizFgPi into a new virtual machine macpro-master-45364cb
05| ==> veertu-anka: Waiting for 2s for clone to boot
```

**Comment by asafg6** [comment]
fixed by https://github.com/veertuinc/packer-builder-veertu-anka/commit/22fd8b2d0c45c626ccf26cb45df52662b8f27f71
