### ISSUE TITLE
Feature Request: Add user mechanism for suspending vm to create a snapshot 

### ISSUE THREAD

**Issue by joshenders** [veertuinc/packer-builder-veertu-anka#9]
Some of the scripts that the shell provisioner runs take a long time (installing xcode for instance) and it would be great if the user could arbitrarily yield to the packer builder at points to create a snapshot for which a later invocation could use as a source VM.

```
packer build template.json
```
Where template.json has a shell provisioner along the lines of of:
```
...
{
      "type": "shell",
      "execute_command": "chmod +x {{ .Path }}; sudo -u {{user `sudo_user`}} {{ .Vars }} {{ .Path }}",
      "scripts": [
        "scripts/10-install-xcode.sh",            # snapshot after this step
        "scripts/20-install-ios-simulators.sh",   # snapshot after this step
        "scripts/30-install-buildkite-agent.sh",  # snapshot after this step

      ],
},
...
```

To achieve something like this currently, packer has to be called several times with several different templates with shell provisioner excerpts. This is of course sub-optimal because splitting configuration across multiple files is difficult to maintain.

Not super familiar with the packer builder API but it seems like this might be possible as the provisioner currently snapshots and then clones after a base macOS install which happens without a separate packer invocation.

**Comment by medicis123** [comment]
Feel free to ping us at Veertu slack or support with any questions on this. We are a little behind in terms of updating this Packer plugin. Planning to do this sometime next month.

**Comment by asafg6** [comment]
@joshenders is this request still relevant?
